export {MenurepresentantesPage} from './menurepresentantes/menurepresentantes';
export {AlumnosRepresentantetabPage} from './alumnos-representantetab/alumnos-representantetab';
export {AsistenciAlumnosRepresentantetabPage} from './asistenci-alumnos-representantetab/asistenci-alumnos-representantetab';
export {DatosAlumnosRepresentantetabPage} from './datos-alumnos-representantetab/datos-alumnos-representantetab';
export {ActualizarDatosAlumnoPage} from './actualizar-datos-alumno/actualizar-datos-alumno'
export {ConsultarAsistenciaAlumnosRepresentantesPage} from './consultar-asistencia-alumnos-representantes/consultar-asistencia-alumnos-representantes'
export {ModalActualizarDatosRepresentantePage} from './modal-actualizar-datos-representante/modal-actualizar-datos-representante';
export {FacturaRepresentantesPage} from './factura-representantes/factura-representantes';
export {SubirimagenesRepresentantesPage} from './subirimagenes-representantes/subirimagenes-representantes';
